#!/bin/bash
# uploadfile
# automatically upload file $1 to $2
# by Haiyong Zheng
# website: http://www.flyzhy.org
#
# Test the Arguments
if [ $# -ne 2 ]; then
echo -ne "Usage: $0 file upload_dir\n"
exit 1
fi
#
# Upload file automatically
ftp -i -in <<EOF
open 211.64.130.238
user haiyong haiyong
!echo "Welcome to haiyong:haiyong@211.64.130.238"
!echo "Upload file $1 to $2"
cd $2
put $1
!echo "Done"
!echo "Bye"
EOF

